export const noop = () => {};

export const electronAPIMock = {
    pickFolder: noop,
    downloadVideoPython: noop,
    saveVideoFile: noop,
    getVideoInfoPython: noop,
    openDirectory: noop,
    openFileInDirectory: noop,
    openFileExternally: noop,
    saveCookie: async () => ({ success: true, cookieCount: 0, skipped: 0 }),
    deleteCookie: async () => ({ success: true }),
    getCookieStatus: async () => ({ loaded: false, cookieCount: 0 }),
    getDownloadDir: async () => ({ downloadDir: '' }),
    setDownloadDir: async () => ({ success: true, downloadDir: '' }),
    checkFileExists: async () => false,
    checkForYtdlpUpdate: async () => ({ current: '', latest: '', updateAvailable: false }),
    startYtdlpUpdate: async () => ({ success: true, version: '' }),
    onYtdlpUpdateProgress: noop,
    removeYtdlpUpdateProgressListener: noop,
    quitApp: noop,
    deleteVideoInfoCacheEntry: async () => ({ success: true, existed: false }),
    getLibraryDir: async () => ({ libraryDir: '' }),
    setLibraryDir: async () => ({ success: true, libraryDir: '' }),
    getThemeMode: async () => ({ themeMode: 'light' }),
    setThemeMode: async () => ({ success: true, themeMode: 'light' }),
    getCustomConvertFormats: async () => ({ customConvertFormats: [] }),
    setCustomConvertFormats: async () => ({ success: true, customConvertFormats: [] }),
    getLibraryIndex: async () => ({ channels: [] }),
    refreshLibraryIndex: async () => ({ channels: [] }),
    refreshChannelIcon: async () => ({ channels: [] }),
    addLibraryEntry: async () => ({ success: true, videoDir: '', epoch: '' }),
    overrideLibraryEntry: async () => ({ success: true, videoDir: '' }),
    addLibraryVersion: async () => ({ success: true, videoDir: '', epoch: '', metadata: {} }),
    findLibraryVideo: async () => ({ found: false }),
    fetchPlaylistEntries: async () => ({ success: true, entries: [] }),
    enrichPlaylistEntry: async () => ({ success: true }),
    recordLibraryDownload: async () => ({ success: true }),
    swapLibraryDownload: async () => ({}),
    deleteLibraryEntry: async () => ({ success: true, videoDeleted: true }),
    onLibraryBackgroundUpdate: noop,
    removeLibraryBackgroundUpdateListener: noop,
    saveExportedFile: async () => ({ canceled: true }),
    extractMp3FromFile: async () => ({ success: true }),
    convertFileFormat: async () => ({ success: true }),
    extractClipFromFile: async () => ({ success: true }),
    embedFileMetadata: async () => ({ success: true }),
    onFfmpegUtilityProgress: noop,
    removeFfmpegUtilityProgressListener: noop,
    reportRendererError: noop,
    getErrorLogInfo: async () => ({ exists: false, path: '' }),
    openErrorLog: noop,

}

export const electronAPIPythonDownloadMock = {
    startDownloadPython: noop,
    onProgressUpdate: noop,
    removeProgressListener: noop,
}